# Generated by Django 5.2.15 on 2026-07-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_auto_20200331_1203"),
        (
            "notifications",
            "0010_rename_notification_recipient_unread_notificatio_recipie_8bedf2_idx",
        ),
    ]

    operations = []
